services:
  - type: web
    name: line-bot-python-flask
    env: python
    repo: https://github.com/willes861219/LineBot
    buildCommand: install --upgrade pip;pip install gunicorn -r requirements.txt
    startCommand: gunicorn app:main
    plan: free
    autoDeploy: false
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
